GET http://localhost:8080/api/list/
Content-Type: application/json
###
POST http://localhost:8080/api/list/
Content-Type: application/json

{
    "title": "Personal List",
    "spaceID": 2
}
###
DELETE http://localhost:8080/api/list/4
###
GET http://localhost:8080/api/space/
Content-Type: application/json
###
POST http://localhost:8080/api/space/
Content-Type: application/json

{
    "title": "Personal Space"
}
###
DELETE http://localhost:8080/api/space/1
###
GET http://localhost:8080/api/tasks/
Content-Type: application/json
###
POST http://localhost:8080/api/tasks/ 
content-type: application/json

{
    "listId": 3,
    "content": "test",
    "description": "testing"
}
###
DELETE http://localhost:8080/api/tasks/3
