GET http://localhost:8080/api/list/
Content-Type: application/json
###
POST http://localhost:8080/api/list/
Content-Type: application/json

{
    "title": "Personal List",
    "spaceID": 2
}
###
DELETE http://localhost:8080/api/list/4
###
GET http://localhost:8080/api/space/
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoidGVzdDJAZW1haWwuY29tIiwiZXhwIjoxNzI1OTE3ODk3fQ.MR5_R-u1xmOHN4hDz2yupIcWYIt9UmRv8YGUXDGc_9Q

###
POST http://localhost:8080/api/space/
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoidGVzdDJAZW1haWwuY29tIiwiZXhwIjoxNzI1OTE3ODk3fQ.MR5_R-u1xmOHN4hDz2yupIcWYIt9UmRv8YGUXDGc_9Q

{
    "title": "Personal Space"
}
###
DELETE http://localhost:8080/api/space/5
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoidGVzdDJAZW1haWwuY29tIiwiZXhwIjoxNzI1OTE3ODk3fQ.MR5_R-u1xmOHN4hDz2yupIcWYIt9UmRv8YGUXDGc_9Q

###
GET http://localhost:8080/api/tasks/
Content-Type: application/json
###
POST http://localhost:8080/api/tasks/ 
content-type: application/json

{
    "listId": 3,
    "content": "test",
    "description": "testing"
}
###
DELETE http://localhost:8080/api/tasks/3
###
POST http://localhost:8080/api/auth/register
content-type: application/json

{
    "email": "test3@email.com",
    "password": "qq11QQ"
}
###
POST http://localhost:8080/api/auth/login
content-type: application/json

{
    "email": "test2@email.com",
    "password": "qq11QQ"
}