GET http://localhost:8080/api/list/
Content-Type: application/json
###
POST http://localhost:8080/api/list/
Content-Type: application/json

{
    "title": "Personal List"
}
###
DELETE http://localhost:8080/api/list/3
###
GET http://localhost:8080/api/tasks/
Content-Type: application/json
###
POST http://localhost:8080/api/tasks/ 
content-type: application/json

{
    "listId": 3,
    "content": "test",
    "description": "testing"
}
###
DELETE http://localhost:8080/api/tasks/3
